name: Amazon ECR Build & Push

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

concurrency:
  group: ecr-push-${{ github.ref }}
  cancel-in-progress: true

jobs:
  push-ecr:
    name: Build & Push ECR (OIDC)
    permissions:
      id-token: write
      contents: read
    uses: oseiasal/.github/.github/workflows/reusable-docker-push.yml@main
    with:
      image-name: '$REPOSITORY_NAME'
      dockerfile-path: 'Dockerfile'
      aws-region: 'us-east-1'
      push-image: true
      tag-latest: true
    secrets:
      AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
      AWS_ROLE_TO_ASSUME: ${{ secrets.AWS_ROLE_TO_ASSUME }}
